# Generated by Django 3.1.4 on 2023-05-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_auto_20230506_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='op5',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
