# Generated by Django 3.1.4 on 2023-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_quesmodel_op5'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='det',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
