# Generated by Django 3.1.4 on 2023-05-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_quesmodel_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='ans',
            field=models.CharField(max_length=200, null=True, verbose_name='答案(A、B、C、D、E)'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='det',
            field=models.TextField(max_length=4000, null=True, verbose_name='詳解'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op1',
            field=models.CharField(max_length=200, null=True, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op2',
            field=models.CharField(max_length=200, null=True, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op3',
            field=models.CharField(max_length=200, null=True, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op4',
            field=models.CharField(max_length=200, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op5',
            field=models.CharField(max_length=200, null=True, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='qid',
            field=models.IntegerField(default=0, verbose_name='題號'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.TextField(max_length=2000, null=True, verbose_name='題目'),
        ),
    ]
